name: Hravka Build

on:
  workflow_dispatch:

jobs:
  build-hravka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --version 0.2.108

      - name: Install JS stuff
        working-directory: web
        run: npm ci

      - name: Build My Hravka
        working-directory: web
        run: npm run build:selfhosted
        env:
          CFG_RELEASE_CHANNEL: nightly

      - name: Upload My Files
        uses: actions/upload-artifact@v4
        with:
          name: hravka-files
          path: web/packages/selfhosted/dist/
